[package]
name = "html2md-rs"
version = "0.12.1"
edition = "2021"
rust-version = "1.70"
description = "Convert HTML to Markdown"
documentation = "https://docs.rs/html2md-rs"
readme = "README.md"
homepage = "https://github.com/izyuumi/html2md-rs"
repository = "https://github.com/izyuumi/html2md-rs"
license = "MIT"
keywords = ["html", "markdown", "html2md", "html-to-markdown", "html-to-md"]
categories = ["parsing"]
exclude = ["/.github", "/.gitignore", "/justfile", "/rustfmt.toml"]
